name: ramp-bike-skore
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - folium
  - matplotlib
  - seaborn
  - pyarrow
  - skore
  - skrub

  - pip
  - pip:
    - ramp-workflow
    - osfclient
